language: android
android:
     before_script:
     - chmod +x gradlew 
     components:
      - tools
      - platform-tools
      - tools

      - build-tools-27.0.3

      - android-27

      - sys-img-armeabi-v7a-android-22


